// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShippingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShippingRequest) Reset() {
	*x = CreateShippingRequest{}
	mi := &file_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingRequest) ProtoMessage() {}

func (x *CreateShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingRequest.ProtoReflect.Descriptor instead.
func (*CreateShippingRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShippingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShippingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateShippingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingId    string                 `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShippingResponse) Reset() {
	*x = CreateShippingResponse{}
	mi := &file_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingResponse) ProtoMessage() {}

func (x *CreateShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingResponse.ProtoReflect.Descriptor instead.
func (*CreateShippingResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShippingResponse) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *CreateShippingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_shipping_proto protoreflect.FileDescriptor

const file_shipping_proto_rawDesc = "" +
	"\n" +
	"\x0eshipping.proto\x12\bshipping\"L\n" +
	"\x15CreateShippingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"Q\n" +
	"\x16CreateShippingResponse\x12\x1f\n" +
	"\vtracking_id\x18\x01 \x01(\tR\n" +
	"trackingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2W\n" +
	"\bShipping\x12K\n" +
	"\x06Create\x12\x1f.shipping.CreateShippingRequest\x1a .shipping.CreateShippingResponseB=Z;github.com/dangthanhduong01/microservices_proto/pb/shippingb\x06proto3"

var (
	file_shipping_proto_rawDescOnce sync.Once
	file_shipping_proto_rawDescData []byte
)

func file_shipping_proto_rawDescGZIP() []byte {
	file_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)))
	})
	return file_shipping_proto_rawDescData
}

var file_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shipping_proto_goTypes = []any{
	(*CreateShippingRequest)(nil),  // 0: shipping.CreateShippingRequest
	(*CreateShippingResponse)(nil), // 1: shipping.CreateShippingResponse
}
var file_shipping_proto_depIdxs = []int32{
	0, // 0: shipping.Shipping.Create:input_type -> shipping.CreateShippingRequest
	1, // 1: shipping.Shipping.Create:output_type -> shipping.CreateShippingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_proto_init() }
func file_shipping_proto_init() {
	if File_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_proto_msgTypes,
	}.Build()
	File_shipping_proto = out.File
	file_shipping_proto_goTypes = nil
	file_shipping_proto_depIdxs = nil
}
