// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice           float32  `protobuf:"fixed32,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateOrderRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *CreateOrderRequest) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

type CreateOrderResponse struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *CreateOrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Item struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Item) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "CreateOrderResponse")
	proto.RegisterType((*Item)(nil), "Item")
}

func init() {
	proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077)
}

var fileDescriptor_cd01338c35d87077 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbf, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xbf, 0xb4, 0x5f, 0x7f, 0xe4, 0xc2, 0xe4, 0x22, 0x11, 0x8a, 0x10, 0x51, 0xa6, 0x4c,
	0x09, 0x94, 0x05, 0x75, 0x84, 0x29, 0x5d, 0x40, 0x66, 0x63, 0x29, 0x69, 0x7c, 0x4a, 0x2c, 0x48,
	0x9c, 0xda, 0x67, 0x24, 0xfe, 0x7b, 0x14, 0x97, 0x02, 0x15, 0x8c, 0xef, 0x23, 0x9d, 0xdf, 0xc7,
	0x77, 0x10, 0x28, 0x2d, 0x50, 0xa7, 0x9d, 0x56, 0xa4, 0xe2, 0x17, 0x60, 0x77, 0x1a, 0x0b, 0xc2,
	0xfb, 0x1e, 0x72, 0xdc, 0x5a, 0x34, 0xc4, 0x4e, 0x60, 0x62, 0x0d, 0xea, 0xb5, 0x14, 0xa1, 0x17,
	0x79, 0xc9, 0x90, 0x8f, 0xfb, 0x98, 0x0b, 0x76, 0x06, 0x23, 0x49, 0xd8, 0x98, 0x70, 0x10, 0x0d,
	0x93, 0x60, 0x31, 0x4a, 0x73, 0xc2, 0x86, 0xef, 0x18, 0xbb, 0x80, 0x80, 0x14, 0x15, 0xaf, 0xeb,
	0x4e, 0xcb, 0x12, 0xc3, 0x61, 0xe4, 0x25, 0x03, 0x0e, 0x0e, 0x3d, 0xf4, 0x24, 0x5e, 0xc1, 0xec,
	0xa0, 0xcc, 0x74, 0xaa, 0x35, 0xc8, 0x4e, 0x61, 0xea, 0x94, 0xbe, 0xeb, 0x26, 0x2e, 0xe7, 0x82,
	0x85, 0x30, 0x69, 0xd0, 0x98, 0xa2, 0xc2, 0x70, 0x10, 0x79, 0x89, 0xcf, 0xf7, 0x31, 0x7e, 0x86,
	0xff, 0x7d, 0x37, 0x3b, 0x07, 0xe8, 0xb4, 0x12, 0xb6, 0xa4, 0xfd, 0xb8, 0xcf, 0xfd, 0x4f, 0x92,
	0x0b, 0x36, 0x87, 0xe9, 0xd6, 0x16, 0x2d, 0x49, 0x7a, 0x77, 0x2f, 0x8c, 0xf8, 0x57, 0xee, 0x47,
	0x6d, 0x2b, 0xe9, 0x40, 0xd7, 0xef, 0x89, 0xb3, 0x5d, 0xac, 0xe0, 0xc8, 0x79, 0x3e, 0xa2, 0x7e,
	0x93, 0x25, 0xb2, 0x25, 0x04, 0x3f, 0xec, 0xd9, 0x2c, 0xfd, 0xbd, 0xb8, 0xf9, 0x71, 0xfa, 0xc7,
	0x07, 0xe3, 0x7f, 0xb7, 0xcb, 0xa7, 0x9b, 0x4a, 0x52, 0x6d, 0x37, 0x69, 0xa9, 0x9a, 0x4c, 0x14,
	0x6d, 0x45, 0x75, 0xd1, 0xd6, 0xc2, 0xaa, 0xb6, 0xba, 0xbc, 0xca, 0x1a, 0x59, 0x6a, 0x65, 0x76,
	0x3d, 0x66, 0xed, 0x2e, 0x93, 0x75, 0x9b, 0xcc, 0x6d, 0x61, 0x33, 0x76, 0xf9, 0xfa, 0x23, 0x00,
	0x00, 0xff, 0xff, 0x33, 0x9d, 0xbf, 0xd3, 0xb8, 0x01, 0x00, 0x00,
}
