// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock                int32    `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Category             string   `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Product) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// ── List ──
type ListProductsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductsRequest) Reset()         { *m = ListProductsRequest{} }
func (m *ListProductsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductsRequest) ProtoMessage()    {}
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *ListProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsRequest.Unmarshal(m, b)
}
func (m *ListProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsRequest.Marshal(b, m, deterministic)
}
func (m *ListProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsRequest.Merge(m, src)
}
func (m *ListProductsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductsRequest.Size(m)
}
func (m *ListProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsRequest proto.InternalMessageInfo

func (m *ListProductsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListProductsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListProductsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type ListProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalCount           int32      `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProductsResponse) Reset()         { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()    {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *ListProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResponse.Unmarshal(m, b)
}
func (m *ListProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResponse.Merge(m, src)
}
func (m *ListProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductsResponse.Size(m)
}
func (m *ListProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResponse proto.InternalMessageInfo

func (m *ListProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *ListProductsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

// ── Detail ──
type GetProductRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

// ── Create ──
type CreateProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock                int32    `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Category             string   `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProductRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateProductRequest) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *CreateProductRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type CreateProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

// ── Update ──
type UpdateProductRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Category             string   `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateProductRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdateProductRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type UpdateProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

// ── Inventory ──
type UpdateStockRequest struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStockRequest) Reset()         { *m = UpdateStockRequest{} }
func (m *UpdateStockRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStockRequest) ProtoMessage()    {}
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *UpdateStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStockRequest.Unmarshal(m, b)
}
func (m *UpdateStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStockRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStockRequest.Merge(m, src)
}
func (m *UpdateStockRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStockRequest.Size(m)
}
func (m *UpdateStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStockRequest proto.InternalMessageInfo

func (m *UpdateStockRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *UpdateStockRequest) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type UpdateStockResponse struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	NewStock             int32    `protobuf:"varint,2,opt,name=new_stock,json=newStock,proto3" json:"new_stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStockResponse) Reset()         { *m = UpdateStockResponse{} }
func (m *UpdateStockResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStockResponse) ProtoMessage()    {}
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *UpdateStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStockResponse.Unmarshal(m, b)
}
func (m *UpdateStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStockResponse.Marshal(b, m, deterministic)
}
func (m *UpdateStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStockResponse.Merge(m, src)
}
func (m *UpdateStockResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStockResponse.Size(m)
}
func (m *UpdateStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStockResponse proto.InternalMessageInfo

func (m *UpdateStockResponse) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *UpdateStockResponse) GetNewStock() int32 {
	if m != nil {
		return m.NewStock
	}
	return 0
}

type GetStockRequest struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStockRequest) Reset()         { *m = GetStockRequest{} }
func (m *GetStockRequest) String() string { return proto.CompactTextString(m) }
func (*GetStockRequest) ProtoMessage()    {}
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{11}
}

func (m *GetStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStockRequest.Unmarshal(m, b)
}
func (m *GetStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStockRequest.Marshal(b, m, deterministic)
}
func (m *GetStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStockRequest.Merge(m, src)
}
func (m *GetStockRequest) XXX_Size() int {
	return xxx_messageInfo_GetStockRequest.Size(m)
}
func (m *GetStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStockRequest proto.InternalMessageInfo

func (m *GetStockRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type GetStockResponse struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock                int32    `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStockResponse) Reset()         { *m = GetStockResponse{} }
func (m *GetStockResponse) String() string { return proto.CompactTextString(m) }
func (*GetStockResponse) ProtoMessage()    {}
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{12}
}

func (m *GetStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStockResponse.Unmarshal(m, b)
}
func (m *GetStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStockResponse.Marshal(b, m, deterministic)
}
func (m *GetStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStockResponse.Merge(m, src)
}
func (m *GetStockResponse) XXX_Size() int {
	return xxx_messageInfo_GetStockResponse.Size(m)
}
func (m *GetStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStockResponse proto.InternalMessageInfo

func (m *GetStockResponse) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetStockResponse) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func init() {
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*ListProductsRequest)(nil), "ListProductsRequest")
	proto.RegisterType((*ListProductsResponse)(nil), "ListProductsResponse")
	proto.RegisterType((*GetProductRequest)(nil), "GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "GetProductResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "CreateProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "UpdateProductResponse")
	proto.RegisterType((*UpdateStockRequest)(nil), "UpdateStockRequest")
	proto.RegisterType((*UpdateStockResponse)(nil), "UpdateStockResponse")
	proto.RegisterType((*GetStockRequest)(nil), "GetStockRequest")
	proto.RegisterType((*GetStockResponse)(nil), "GetStockResponse")
}

func init() {
	proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5)
}

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x6f, 0xd3, 0x4c,
	0x14, 0x8c, 0x9d, 0xba, 0x75, 0x5e, 0xbe, 0xf6, 0x6b, 0x37, 0x4e, 0x65, 0xb9, 0xaa, 0xb0, 0x16,
	0x0e, 0x39, 0x6d, 0xda, 0x72, 0x00, 0x15, 0x90, 0x28, 0x3d, 0x54, 0x48, 0x48, 0x80, 0x23, 0x2e,
	0x48, 0xc8, 0x72, 0xec, 0x55, 0x62, 0x41, 0xbc, 0xae, 0xbd, 0xa6, 0x6a, 0x7f, 0x04, 0x27, 0xfe,
	0x1a, 0xbf, 0x86, 0x0b, 0xf2, 0x7a, 0x9d, 0xda, 0x8e, 0xdb, 0x12, 0x89, 0x53, 0xbc, 0xb3, 0xeb,
	0xb7, 0x33, 0x6f, 0xe6, 0xc5, 0xb0, 0x1d, 0x27, 0x2c, 0xc8, 0x7c, 0x4e, 0xe2, 0x84, 0x71, 0x86,
	0x7f, 0x29, 0xb0, 0xf5, 0xa1, 0x40, 0xd0, 0x0e, 0xa8, 0x61, 0x60, 0x2a, 0xb6, 0x32, 0xea, 0x3a,
	0x6a, 0x18, 0x20, 0x04, 0x1b, 0x91, 0xb7, 0xa0, 0xa6, 0x6a, 0x2b, 0xa3, 0x9e, 0x23, 0x9e, 0x91,
	0x0d, 0xfd, 0x80, 0xa6, 0x7e, 0x12, 0xc6, 0x3c, 0x64, 0x91, 0xd9, 0x15, 0x5b, 0x55, 0x08, 0x19,
	0xa0, 0xc5, 0x49, 0xe8, 0x53, 0x73, 0xc3, 0x56, 0x46, 0xaa, 0x53, 0x2c, 0x72, 0x34, 0xe5, 0xcc,
	0xff, 0x6a, 0x6a, 0xb6, 0x32, 0xd2, 0x9c, 0x62, 0x81, 0x2c, 0xd0, 0x7d, 0x8f, 0xd3, 0x19, 0x4b,
	0xae, 0xcd, 0x4d, 0x51, 0x6a, 0xb9, 0x46, 0x87, 0x00, 0x7e, 0x42, 0x3d, 0x4e, 0x03, 0xd7, 0xe3,
	0xe6, 0x96, 0x60, 0xd5, 0x93, 0xc8, 0x19, 0xcf, 0xb7, 0xb3, 0x38, 0x28, 0xb7, 0xf5, 0x62, 0x5b,
	0x22, 0x67, 0x1c, 0x4f, 0x61, 0xf0, 0x2e, 0x4c, 0xb9, 0x94, 0x96, 0x3a, 0xf4, 0x32, 0xa3, 0x29,
	0xcf, 0x25, 0xc5, 0xde, 0x8c, 0x0a, 0x91, 0x9a, 0x23, 0x9e, 0xd1, 0x01, 0xf4, 0xf2, 0x5f, 0x37,
	0x0d, 0x6f, 0x0a, 0xad, 0x9a, 0xa3, 0xe7, 0xc0, 0x24, 0xbc, 0xa1, 0x35, 0x86, 0xdd, 0x3a, 0x43,
	0xfc, 0x05, 0x8c, 0xfa, 0x1d, 0x69, 0xcc, 0xa2, 0x94, 0xa2, 0x27, 0xa0, 0xcb, 0x26, 0xa7, 0xa6,
	0x62, 0x77, 0x47, 0xfd, 0x13, 0x9d, 0xc8, 0x43, 0xce, 0x72, 0x07, 0x3d, 0x82, 0x3e, 0x67, 0xdc,
	0xfb, 0xe6, 0xfa, 0x2c, 0x8b, 0xb8, 0xbc, 0x18, 0x04, 0x74, 0x9e, 0x23, 0xf8, 0x31, 0xec, 0x5d,
	0xd0, 0xb2, 0x7a, 0x29, 0xa0, 0xe1, 0x11, 0x7e, 0x0e, 0xa8, 0x7a, 0x48, 0x32, 0xc0, 0xb0, 0x25,
	0xef, 0x11, 0x47, 0xab, 0x04, 0xca, 0x0d, 0xfc, 0x53, 0x01, 0xe3, 0x5c, 0xb4, 0xb3, 0x71, 0x45,
	0x69, 0xbb, 0x72, 0xb7, 0xed, 0xea, 0x3d, 0xb6, 0x77, 0x5b, 0x6d, 0xdf, 0xb8, 0xcb, 0x76, 0xad,
	0xd1, 0xd4, 0x17, 0x30, 0x6c, 0xb0, 0x5a, 0x43, 0xd3, 0x0f, 0x05, 0x8c, 0x4f, 0x22, 0x03, 0xf7,
	0xb7, 0xed, 0x9f, 0x46, 0xfb, 0x01, 0x35, 0x0d, 0x3e, 0x6b, 0xa8, 0x79, 0x0f, 0xa8, 0x78, 0x79,
	0x92, 0x77, 0xad, 0x94, 0x72, 0x08, 0x20, 0x0f, 0xb8, 0x4b, 0x49, 0x3d, 0x89, 0xbc, 0x0d, 0x72,
	0x36, 0x97, 0x99, 0x17, 0xf1, 0x90, 0x5f, 0x97, 0x61, 0x2e, 0xd7, 0xf8, 0x23, 0x0c, 0x6a, 0x05,
	0x25, 0x97, 0x07, 0x2a, 0x1e, 0x40, 0x2f, 0xa2, 0x57, 0x6e, 0xe1, 0xa3, 0x2c, 0x19, 0xd1, 0x2b,
	0x51, 0x03, 0x1f, 0xc1, 0xff, 0x17, 0x94, 0xaf, 0x41, 0x10, 0x5f, 0xc0, 0xee, 0xed, 0x1b, 0x7f,
	0xc7, 0x60, 0x99, 0x22, 0xb5, 0x92, 0xa2, 0x93, 0xdf, 0x2a, 0xec, 0xc8, 0x9e, 0x4d, 0x68, 0xf2,
	0x3d, 0xb7, 0xe2, 0x15, 0xfc, 0x57, 0x9d, 0x48, 0x64, 0x90, 0x96, 0x3f, 0x01, 0x6b, 0x48, 0xda,
	0xc6, 0x16, 0x77, 0xd0, 0x33, 0x80, 0xdb, 0x61, 0x42, 0x88, 0xac, 0x8c, 0x9f, 0x35, 0x20, 0xab,
	0xd3, 0x86, 0x3b, 0xe8, 0x35, 0x6c, 0xd7, 0x42, 0x8b, 0x86, 0xa4, 0x6d, 0xb4, 0xac, 0x7d, 0xd2,
	0x9a, 0xed, 0xa2, 0x42, 0x2d, 0x28, 0x68, 0x48, 0xda, 0x82, 0x6c, 0xed, 0x93, 0xd6, 0x3c, 0xe1,
	0x0e, 0x3a, 0x85, 0x7e, 0xc5, 0x5c, 0x34, 0x20, 0xab, 0xd9, 0xb1, 0x0c, 0xd2, 0xe2, 0x3f, 0xee,
	0xa0, 0x63, 0xd0, 0x4b, 0x4f, 0xd0, 0x2e, 0x69, 0x18, 0x6a, 0xed, 0x91, 0xa6, 0x61, 0xb8, 0xf3,
	0xe6, 0xe5, 0xe7, 0xd3, 0x59, 0xc8, 0xe7, 0xd9, 0x94, 0xf8, 0x6c, 0x31, 0x0e, 0xbc, 0x68, 0xc6,
	0xe7, 0x5e, 0x34, 0x0f, 0x32, 0x16, 0xcd, 0x8e, 0x8e, 0xc7, 0x8b, 0xd0, 0x4f, 0x58, 0x5a, 0xd8,
	0x92, 0xba, 0xe2, 0x5b, 0x33, 0x8e, 0xa7, 0x63, 0xe9, 0xe9, 0x74, 0x53, 0x20, 0x4f, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x82, 0xfc, 0x4e, 0xde, 0x8e, 0x06, 0x00, 0x00,
}
