// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x1a\x11create_user.proto\x1a\x10login_user.proto\x1a\x11update_user.proto\x1a\x12verify_email.proto2\xeb\x01\n" +
	"\vAuthService\x127\n" +
	"\fRegisterUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x122\n" +
	"\tLoginUser\x12\x11.LoginUserRequest\x1a\x12.LoginUserResponse\x125\n" +
	"\n" +
	"UpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\x128\n" +
	"\vVerifyEmail\x12\x13.VerifyEmailRequest\x1a\x14.VerifyEmailResponseB9Z7github.com/dangthanhduong01/microservices_proto/pb/authb\x06proto3"

var file_auth_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: CreateUserRequest
	(*LoginUserRequest)(nil),    // 1: LoginUserRequest
	(*UpdateUserRequest)(nil),   // 2: UpdateUserRequest
	(*VerifyEmailRequest)(nil),  // 3: VerifyEmailRequest
	(*CreateUserResponse)(nil),  // 4: CreateUserResponse
	(*LoginUserResponse)(nil),   // 5: LoginUserResponse
	(*UpdateUserResponse)(nil),  // 6: UpdateUserResponse
	(*VerifyEmailResponse)(nil), // 7: VerifyEmailResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: AuthService.RegisterUser:input_type -> CreateUserRequest
	1, // 1: AuthService.LoginUser:input_type -> LoginUserRequest
	2, // 2: AuthService.UpdateUser:input_type -> UpdateUserRequest
	3, // 3: AuthService.VerifyEmail:input_type -> VerifyEmailRequest
	4, // 4: AuthService.RegisterUser:output_type -> CreateUserResponse
	5, // 5: AuthService.LoginUser:output_type -> LoginUserResponse
	6, // 6: AuthService.UpdateUser:output_type -> UpdateUserResponse
	7, // 7: AuthService.VerifyEmail:output_type -> VerifyEmailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_create_user_proto_init()
	file_login_user_proto_init()
	file_update_user_proto_init()
	file_verify_email_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
