// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type RegisterUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{1}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{3}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	User                 *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId            string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken          string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiry    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=access_token_expiry,json=accessTokenExpiry,proto3" json:"access_token_expiry,omitempty"`
	RefreshTokenExpiry   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expiry,json=refreshTokenExpiry,proto3" json:"refresh_token_expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{4}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginUserResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *LoginUserResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginUserResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginUserResponse) GetAccessTokenExpiry() *timestamppb.Timestamp {
	if m != nil {
		return m.AccessTokenExpiry
	}
	return nil
}

func (m *LoginUserResponse) GetRefreshTokenExpiry() *timestamppb.Timestamp {
	if m != nil {
		return m.RefreshTokenExpiry
	}
	return nil
}

type LogoutUserRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutUserRequest) Reset()         { *m = LogoutUserRequest{} }
func (m *LogoutUserRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutUserRequest) ProtoMessage()    {}
func (*LogoutUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{5}
}

func (m *LogoutUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutUserRequest.Unmarshal(m, b)
}
func (m *LogoutUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutUserRequest.Marshal(b, m, deterministic)
}
func (m *LogoutUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutUserRequest.Merge(m, src)
}
func (m *LogoutUserRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutUserRequest.Size(m)
}
func (m *LogoutUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutUserRequest proto.InternalMessageInfo

func (m *LogoutUserRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutUserResponse) Reset()         { *m = LogoutUserResponse{} }
func (m *LogoutUserResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutUserResponse) ProtoMessage()    {}
func (*LogoutUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{6}
}

func (m *LogoutUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutUserResponse.Unmarshal(m, b)
}
func (m *LogoutUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutUserResponse.Marshal(b, m, deterministic)
}
func (m *LogoutUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutUserResponse.Merge(m, src)
}
func (m *LogoutUserResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutUserResponse.Size(m)
}
func (m *LogoutUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutUserResponse proto.InternalMessageInfo

func (m *LogoutUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{7}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{8}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type VerifyEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{9}
}

func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (m *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(m, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyEmailRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type VerifyEmailResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailResponse) Reset()         { *m = VerifyEmailResponse{} }
func (m *VerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailResponse) ProtoMessage()    {}
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{10}
}

func (m *VerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailResponse.Unmarshal(m, b)
}
func (m *VerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailResponse.Marshal(b, m, deterministic)
}
func (m *VerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailResponse.Merge(m, src)
}
func (m *VerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailResponse.Size(m)
}
func (m *VerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailResponse proto.InternalMessageInfo

func (m *VerifyEmailResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*RegisterUserRequest)(nil), "RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "RegisterUserResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "LoginUserResponse")
	proto.RegisterType((*LogoutUserRequest)(nil), "LogoutUserRequest")
	proto.RegisterType((*LogoutUserResponse)(nil), "LogoutUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "UpdateUserResponse")
	proto.RegisterType((*VerifyEmailRequest)(nil), "VerifyEmailRequest")
	proto.RegisterType((*VerifyEmailResponse)(nil), "VerifyEmailResponse")
}

func init() {
	proto.RegisterFile("auth/auth.proto", fileDescriptor_712ec48c1eaf43a2)
}

var fileDescriptor_712ec48c1eaf43a2 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x95, 0xf3, 0xa5, 0xfd, 0xe2, 0x49, 0x80, 0x66, 0x13, 0xa4, 0x60, 0x84, 0x28, 0xe6, 0xa6,
	0x12, 0xd2, 0x9a, 0x86, 0x1f, 0x81, 0xb8, 0x0a, 0xa8, 0x17, 0x54, 0x15, 0x17, 0xa6, 0x05, 0x89,
	0x1b, 0xcb, 0xb1, 0x37, 0xf6, 0x8a, 0xd8, 0x6b, 0xf6, 0xa7, 0xd0, 0x3b, 0xde, 0x88, 0x37, 0xe0,
	0x95, 0x78, 0x05, 0xe4, 0xb5, 0x1d, 0xd6, 0x49, 0x50, 0x2a, 0x71, 0x53, 0x75, 0x66, 0x67, 0xce,
	0x39, 0x73, 0x3c, 0x13, 0xb8, 0x15, 0x2a, 0x99, 0x7a, 0xe5, 0x1f, 0x5c, 0x70, 0x26, 0x99, 0x73,
	0x3f, 0x61, 0x2c, 0x59, 0x12, 0x4f, 0x47, 0x73, 0xb5, 0xf0, 0x24, 0xcd, 0x88, 0x90, 0x61, 0x56,
	0x54, 0x05, 0xee, 0x4f, 0x0b, 0xba, 0x17, 0x82, 0x70, 0x74, 0x13, 0x3a, 0x34, 0x9e, 0x58, 0x87,
	0xd6, 0x91, 0xed, 0x77, 0x68, 0x8c, 0x1c, 0xe8, 0x29, 0x41, 0x78, 0x1e, 0x66, 0x64, 0xd2, 0xd1,
	0xd9, 0x55, 0x8c, 0xc6, 0xb0, 0x47, 0xb2, 0x90, 0x2e, 0x27, 0xff, 0xe9, 0x87, 0x2a, 0x40, 0x2f,
	0x01, 0x22, 0x4e, 0x42, 0x49, 0xe2, 0x20, 0x94, 0x93, 0xee, 0xa1, 0x75, 0xd4, 0x9f, 0x3a, 0xb8,
	0x12, 0x80, 0x1b, 0x01, 0xf8, 0xbc, 0x11, 0xe0, 0xdb, 0x75, 0xf5, 0x4c, 0x96, 0xad, 0xaa, 0x88,
	0x9b, 0xd6, 0xbd, 0xdd, 0xad, 0x75, 0xf5, 0x4c, 0xba, 0xdf, 0x2d, 0x18, 0xf9, 0x24, 0xa1, 0x42,
	0x12, 0x5e, 0x0e, 0xe2, 0x93, 0x2f, 0x8a, 0x08, 0xd9, 0xd2, 0x6f, 0xad, 0xe9, 0xbf, 0x0b, 0xf6,
	0x42, 0x2d, 0x97, 0x81, 0x39, 0x5c, 0x99, 0x78, 0xf7, 0xf7, 0xe1, 0x1c, 0xe8, 0x15, 0xa1, 0x10,
	0x5f, 0x19, 0x8f, 0xf5, 0x68, 0xb6, 0xbf, 0x8a, 0xdd, 0x63, 0x18, 0xb7, 0x15, 0x88, 0x82, 0xe5,
	0x82, 0xa0, 0x3b, 0xd0, 0x2d, 0x29, 0x35, 0x7d, 0x7f, 0xba, 0x87, 0xf5, 0xa3, 0x4e, 0xb9, 0xa7,
	0x70, 0x70, 0xc6, 0x12, 0x9a, 0x5f, 0x57, 0xb1, 0x49, 0xdf, 0x59, 0xa3, 0xff, 0xd1, 0x81, 0xa1,
	0x01, 0xb6, 0x93, 0x1c, 0xdd, 0x03, 0x10, 0x44, 0x08, 0xca, 0xf2, 0x80, 0x36, 0x70, 0x76, 0x9d,
	0x79, 0x1b, 0xa3, 0x07, 0x30, 0x08, 0xa3, 0x88, 0x08, 0x11, 0x48, 0xf6, 0x99, 0xe4, 0xb5, 0x0f,
	0xfd, 0x2a, 0x77, 0x5e, 0xa6, 0xd0, 0x43, 0xb8, 0xc1, 0xc9, 0x82, 0x13, 0x91, 0xd6, 0x35, 0x95,
	0x25, 0x83, 0x3a, 0x59, 0x15, 0x9d, 0xc2, 0xc8, 0xc4, 0x09, 0xc8, 0xb7, 0x82, 0xf2, 0xab, 0x6b,
	0x7c, 0xdd, 0xa1, 0x41, 0x75, 0xa2, 0x9b, 0xd0, 0x19, 0x8c, 0x5b, 0x84, 0x0d, 0xd8, 0xfe, 0x4e,
	0x30, 0x64, 0x6a, 0xaa, 0xd0, 0xdc, 0xa9, 0x36, 0x8c, 0x29, 0x69, 0xda, 0xdf, 0x76, 0xc5, 0x5a,
	0x73, 0xc5, 0xc5, 0x80, 0xcc, 0x9e, 0xda, 0xe5, 0x09, 0xfc, 0x2f, 0x94, 0x56, 0xab, 0x3b, 0x7a,
	0x7e, 0x13, 0xba, 0x1c, 0x86, 0x17, 0x7a, 0x49, 0x4d, 0x8e, 0x7f, 0x3f, 0xb2, 0xd6, 0xea, 0x76,
	0xdb, 0xab, 0xeb, 0x7a, 0x80, 0x4c, 0xce, 0xdd, 0x6b, 0xf8, 0x11, 0xd0, 0x07, 0xc2, 0xe9, 0xe2,
	0xea, 0xa4, 0x04, 0x6f, 0x54, 0xae, 0x98, 0x2d, 0x93, 0xf9, 0x11, 0x0c, 0x2f, 0xcb, 0x5a, 0x1a,
	0x85, 0xb2, 0x34, 0x29, 0x62, 0x71, 0x23, 0xfa, 0xc0, 0x7c, 0x78, 0xc3, 0xe2, 0x52, 0xc9, 0xa8,
	0x05, 0xbc, 0xcb, 0xae, 0xe9, 0x2f, 0x0b, 0xfa, 0x33, 0x25, 0xd3, 0xf7, 0x84, 0x5f, 0xd2, 0x88,
	0xa0, 0x57, 0x30, 0x30, 0x6f, 0x0a, 0x8d, 0xf1, 0x96, 0x23, 0x77, 0x6e, 0xe3, 0xad, 0x87, 0x37,
	0x05, 0x7b, 0x75, 0x10, 0x68, 0x88, 0xd7, 0x2f, 0xcd, 0x41, 0x78, 0xf3, 0x5e, 0x9e, 0x01, 0xfc,
	0xf1, 0x0e, 0x21, 0xbc, 0xf1, 0xf1, 0x9c, 0x11, 0xde, 0x62, 0xee, 0x0b, 0xe8, 0x1b, 0x83, 0xa2,
	0x11, 0xde, 0xf4, 0xd3, 0x19, 0xe3, 0x2d, 0x5e, 0xbc, 0x7e, 0xfe, 0xe9, 0x69, 0x42, 0x65, 0xaa,
	0xe6, 0x38, 0x62, 0x99, 0x17, 0x87, 0x79, 0x22, 0xd3, 0x30, 0x4f, 0x63, 0xc5, 0xf2, 0xe4, 0xf1,
	0xb1, 0x97, 0xd1, 0x88, 0x33, 0x51, 0xb9, 0x21, 0x02, 0xbd, 0xd8, 0xfa, 0x87, 0x7d, 0xbe, 0xaf,
	0xff, 0x7f, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x51, 0xc1, 0x3e, 0x15, 0xec, 0x05, 0x00, 0x00,
}
