// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login_user.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac54452ffdd00d57, []int{0}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	User                 *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId            string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken          string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiry    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=access_token_expiry,json=accessTokenExpiry,proto3" json:"access_token_expiry,omitempty"`
	RefreshTokenExpiry   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expiry,json=refreshTokenExpiry,proto3" json:"refresh_token_expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac54452ffdd00d57, []int{1}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginUserResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *LoginUserResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginUserResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginUserResponse) GetAccessTokenExpiry() *timestamppb.Timestamp {
	if m != nil {
		return m.AccessTokenExpiry
	}
	return nil
}

func (m *LoginUserResponse) GetRefreshTokenExpiry() *timestamppb.Timestamp {
	if m != nil {
		return m.RefreshTokenExpiry
	}
	return nil
}

type LogoutUserRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutUserRequest) Reset()         { *m = LogoutUserRequest{} }
func (m *LogoutUserRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutUserRequest) ProtoMessage()    {}
func (*LogoutUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac54452ffdd00d57, []int{2}
}

func (m *LogoutUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutUserRequest.Unmarshal(m, b)
}
func (m *LogoutUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutUserRequest.Marshal(b, m, deterministic)
}
func (m *LogoutUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutUserRequest.Merge(m, src)
}
func (m *LogoutUserRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutUserRequest.Size(m)
}
func (m *LogoutUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutUserRequest proto.InternalMessageInfo

func (m *LogoutUserRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutUserResponse) Reset()         { *m = LogoutUserResponse{} }
func (m *LogoutUserResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutUserResponse) ProtoMessage()    {}
func (*LogoutUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac54452ffdd00d57, []int{3}
}

func (m *LogoutUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutUserResponse.Unmarshal(m, b)
}
func (m *LogoutUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutUserResponse.Marshal(b, m, deterministic)
}
func (m *LogoutUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutUserResponse.Merge(m, src)
}
func (m *LogoutUserResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutUserResponse.Size(m)
}
func (m *LogoutUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutUserResponse proto.InternalMessageInfo

func (m *LogoutUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*LoginUserRequest)(nil), "LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "LoginUserResponse")
	proto.RegisterType((*LogoutUserRequest)(nil), "LogoutUserRequest")
	proto.RegisterType((*LogoutUserResponse)(nil), "LogoutUserResponse")
}

func init() {
	proto.RegisterFile("login_user.proto", fileDescriptor_ac54452ffdd00d57)
}

var fileDescriptor_ac54452ffdd00d57 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4f, 0xe3, 0x40,
	0x10, 0xc5, 0x95, 0x5c, 0x92, 0x4b, 0x26, 0x39, 0x29, 0xd9, 0xbb, 0xc2, 0x17, 0x09, 0x01, 0xa6,
	0xa1, 0xb2, 0x21, 0x14, 0x88, 0x16, 0x89, 0x82, 0x28, 0x95, 0x15, 0x1a, 0x1a, 0xcb, 0x7f, 0x26,
	0xf6, 0x8a, 0x78, 0xd7, 0xec, 0xec, 0xf2, 0xe7, 0x53, 0xf1, 0x15, 0x91, 0xd7, 0x36, 0x72, 0x68,
	0xe8, 0xf6, 0xbd, 0x79, 0xf3, 0xdb, 0xd1, 0x83, 0xf9, 0x5e, 0x66, 0x5c, 0x84, 0x86, 0x50, 0x79,
	0xa5, 0x92, 0x5a, 0x2e, 0xa1, 0xf3, 0x3e, 0xce, 0xa4, 0xcc, 0xf6, 0xe8, 0x5b, 0x15, 0x9b, 0x9d,
	0xaf, 0x79, 0x81, 0xa4, 0xa3, 0xa2, 0xac, 0x03, 0xee, 0x1a, 0xe6, 0x9b, 0x0a, 0xf0, 0x40, 0xa8,
	0x02, 0x7c, 0x36, 0x48, 0x9a, 0x2d, 0x61, 0x5c, 0x21, 0x44, 0x54, 0xa0, 0xd3, 0x3b, 0xe9, 0x9d,
	0x4f, 0x82, 0x2f, 0x5d, 0xcd, 0xca, 0x88, 0xe8, 0x55, 0xaa, 0xd4, 0xe9, 0xd7, 0xb3, 0x56, 0xbb,
	0x1f, 0x7d, 0x58, 0x74, 0x60, 0x54, 0x4a, 0x41, 0xc8, 0xfe, 0xc3, 0xa0, 0xda, 0xb6, 0xa4, 0xe9,
	0x6a, 0xe8, 0xd9, 0xa1, 0xb5, 0xd8, 0x11, 0x00, 0x21, 0x11, 0x97, 0x22, 0xe4, 0x2d, 0x6e, 0xd2,
	0x38, 0xf7, 0x29, 0x3b, 0x85, 0x59, 0x94, 0x24, 0x48, 0x14, 0x6a, 0xf9, 0x84, 0xc2, 0xf9, 0x65,
	0x03, 0xd3, 0xda, 0xdb, 0x56, 0x16, 0x3b, 0x83, 0x3f, 0x0a, 0x77, 0x0a, 0x29, 0x6f, 0x32, 0x03,
	0x9b, 0x99, 0x35, 0x66, 0x1d, 0x5a, 0xc3, 0xdf, 0x2e, 0x27, 0xc4, 0xb7, 0x92, 0xab, 0x77, 0x67,
	0x68, 0x0f, 0x5a, 0x7a, 0x75, 0x45, 0x5e, 0x5b, 0x91, 0xb7, 0x6d, 0x2b, 0x0a, 0x16, 0x9d, 0xaf,
	0xee, 0xec, 0x12, 0xdb, 0xc0, 0xbf, 0x83, 0x0f, 0x5b, 0xd8, 0xe8, 0x47, 0x18, 0xeb, 0xde, 0x54,
	0xd3, 0xdc, 0x95, 0x2d, 0x4c, 0x1a, 0xdd, 0xad, 0xff, 0xb0, 0x95, 0xde, 0xb7, 0x56, 0x5c, 0x0f,
	0x58, 0x77, 0xa7, 0x69, 0xd9, 0x81, 0xdf, 0x64, 0xec, 0xb5, 0x76, 0x63, 0x1c, 0xb4, 0xf2, 0xf6,
	0xe6, 0xf1, 0x3a, 0xe3, 0x3a, 0x37, 0xb1, 0x97, 0xc8, 0xc2, 0x4f, 0x23, 0x91, 0xe9, 0x3c, 0x12,
	0x79, 0x6a, 0xa4, 0xc8, 0x2e, 0x2e, 0xfd, 0x82, 0x27, 0x4a, 0x12, 0xaa, 0x17, 0x9e, 0x20, 0x85,
	0xf6, 0x6e, 0xbf, 0x8c, 0xfd, 0xc8, 0xe8, 0x3c, 0x1e, 0x59, 0x79, 0xf5, 0x19, 0x00, 0x00, 0xff,
	0xff, 0x01, 0x97, 0xa5, 0x16, 0x64, 0x02, 0x00, 0x00,
}
