// Code generated by protoc-gen-go. DO NOT EDIT.
// source: update_user.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe3fa2a1baa3303, []int{0}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe3fa2a1baa3303, []int{1}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateUserRequest)(nil), "UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "UpdateUserResponse")
}

func init() {
	proto.RegisterFile("update_user.proto", fileDescriptor_8fe3fa2a1baa3303)
}

var fileDescriptor_8fe3fa2a1baa3303 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3b, 0x4b, 0xc5, 0x40,
	0x10, 0x85, 0xb9, 0xf1, 0x5e, 0x31, 0x23, 0x08, 0x59, 0x2c, 0x62, 0x6c, 0x24, 0x95, 0x55, 0xd6,
	0x47, 0x21, 0xb6, 0xfe, 0x00, 0x8b, 0x40, 0x1a, 0x9b, 0xb0, 0xc9, 0x8e, 0xd9, 0x85, 0xec, 0xc3,
	0x7d, 0xf8, 0xfb, 0x25, 0x13, 0x50, 0xbb, 0x39, 0xe7, 0xcc, 0x37, 0x87, 0x81, 0x2a, 0x7b, 0x29,
	0x12, 0x8e, 0x39, 0x62, 0xe8, 0x7c, 0x70, 0xc9, 0x35, 0xf0, 0x37, 0xb7, 0x01, 0xaa, 0x81, 0x16,
	0x86, 0x88, 0xa1, 0xc7, 0xaf, 0x8c, 0x31, 0xb1, 0x2b, 0x28, 0xb4, 0xac, 0x0f, 0x77, 0x87, 0xfb,
	0xb2, 0x2f, 0xb4, 0x64, 0x0d, 0x5c, 0x6c, 0x88, 0x15, 0x06, 0xeb, 0x82, 0xdc, 0x5f, 0xcd, 0xae,
	0xe1, 0x84, 0x46, 0xe8, 0xb5, 0x3e, 0xa3, 0x60, 0x17, 0xec, 0x16, 0xca, 0xcf, 0xbc, 0xae, 0x23,
	0x21, 0xc7, 0x1d, 0xd9, 0x8c, 0x77, 0x61, 0xb0, 0xe5, 0xc0, 0xfe, 0x77, 0x46, 0xef, 0x6c, 0x44,
	0x76, 0x03, 0xc7, 0xed, 0x28, 0xd5, 0x5e, 0x3e, 0x9d, 0x3a, 0x0a, 0xc9, 0x7a, 0x7b, 0xfd, 0x78,
	0x59, 0x74, 0x52, 0x79, 0xea, 0x66, 0x67, 0xb8, 0x14, 0x76, 0x49, 0x4a, 0x58, 0x25, 0xb3, 0xb3,
	0xcb, 0xc3, 0x23, 0x37, 0x7a, 0x0e, 0x2e, 0x62, 0xf8, 0xd6, 0x33, 0xc6, 0x91, 0xfe, 0xe2, 0x7e,
	0xe2, 0x22, 0x27, 0x35, 0x9d, 0x93, 0x7c, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xca, 0x73,
	0xc7, 0x07, 0x01, 0x00, 0x00,
}
