// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verify_email.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f4be9d8481e390, []int{0}
}

func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (m *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(m, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyEmailRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type VerifyEmailResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailResponse) Reset()         { *m = VerifyEmailResponse{} }
func (m *VerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailResponse) ProtoMessage()    {}
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f4be9d8481e390, []int{1}
}

func (m *VerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailResponse.Unmarshal(m, b)
}
func (m *VerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailResponse.Marshal(b, m, deterministic)
}
func (m *VerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailResponse.Merge(m, src)
}
func (m *VerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailResponse.Size(m)
}
func (m *VerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailResponse proto.InternalMessageInfo

func (m *VerifyEmailResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*VerifyEmailRequest)(nil), "VerifyEmailRequest")
	proto.RegisterType((*VerifyEmailResponse)(nil), "VerifyEmailResponse")
}

func init() {
	proto.RegisterFile("verify_email.proto", fileDescriptor_d7f4be9d8481e390)
}

var fileDescriptor_d7f4be9d8481e390 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x3f, 0xab, 0xc2, 0x30,
	0x14, 0x47, 0xe9, 0x83, 0xf7, 0x2f, 0xd3, 0x7b, 0xd1, 0xa1, 0xa3, 0x74, 0x12, 0x84, 0x46, 0x71,
	0x10, 0x57, 0xc5, 0x2f, 0xd0, 0x41, 0xc1, 0xa5, 0xa4, 0xc9, 0xb5, 0x09, 0xd8, 0xdc, 0x9a, 0x9b,
	0x14, 0xfc, 0xf6, 0x62, 0x44, 0xd0, 0xf1, 0xfc, 0xee, 0xe1, 0x70, 0x19, 0x1f, 0xc0, 0xdb, 0xd3,
	0xb5, 0x86, 0x4e, 0xda, 0x73, 0xd9, 0x7b, 0x0c, 0x58, 0x1c, 0x18, 0xdf, 0xa7, 0x75, 0x77, 0x1f,
	0x2b, 0xb8, 0x44, 0xa0, 0xc0, 0xc7, 0xec, 0x33, 0x49, 0x79, 0x36, 0xc9, 0xa6, 0xbf, 0xd5, 0x03,
	0xf8, 0x8c, 0xfd, 0xa7, 0x82, 0x55, 0x32, 0x58, 0x74, 0xb5, 0x42, 0x0d, 0xf9, 0x47, 0x32, 0xfe,
	0x5e, 0x0f, 0x5b, 0xd4, 0x50, 0x08, 0x36, 0x7a, 0x0b, 0x53, 0x8f, 0x8e, 0x80, 0xe7, 0xec, 0x9b,
	0xa2, 0x52, 0x40, 0x94, 0xda, 0x3f, 0xd5, 0x13, 0x37, 0xeb, 0xe3, 0xaa, 0xb5, 0xc1, 0xc4, 0xa6,
	0x54, 0xd8, 0x09, 0x2d, 0x5d, 0x1b, 0x8c, 0x74, 0x46, 0x47, 0x74, 0xed, 0x7c, 0x21, 0x3a, 0xab,
	0x3c, 0x12, 0xf8, 0xc1, 0x2a, 0xa0, 0x3a, 0x3d, 0x2f, 0xfa, 0x46, 0xc8, 0x18, 0x4c, 0xf3, 0x95,
	0x70, 0x79, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x81, 0x8b, 0xd2, 0xd5, 0xe1, 0x00, 0x00, 0x00,
}
