name: "Protocol Buffers Generation"
on:
  push:
    tags:
      - v**
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: "Generate Protocol Buffers"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order", "payment", "shipping", "auth"]
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24
      - uses: actions/checkout@v3
      - name: Install Protocol Buffers Compiler
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Install Protocol Buffers Compiler"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com